kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: private-repository-k8s
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
