apiVersion: v1
kind: Namespace
metadata:
  name: theia
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: theia-python
  namespace: theia
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
  - hosts:
    - theia.matrix
    secretName: theia-prod
  rules:
  - host: theia.matrix
    http:
      paths:
      - backend:
          serviceName: theia-python
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: theia-python
 namespace: theia
spec:
 ports:
 - port: 80
   targetPort: 3000
 selector:
   app: theia-python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia-python
  name: theia-python
  namespace: theia
spec:
  selector:
    matchLabels:
      app: theia-python
  replicas: 1
  template:
    metadata:
      labels:
        app: theia-python
    spec:
      containers:
      - image: theiaide/theia:next
        imagePullPolicy: Always
        name: theia-python
        ports:
        - containerPort: 3000