# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: certmanager-app
#   namespace: argocd
# spec:
#   destination:
#     namespace: cert-manager
#     server: https://kubernetes.default.svc
#   project: infra-project
#   source:
#     repoURL: 'https://github.com/argoproj/argoproj-deployments'
#     path: cert-manager
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=false
#     automated:
#       selfHeal: true
#       prune: true

