apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-app
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    helm:
      path: ''
      repoURL: 'https://charts.jetstack.io'
      # targetRevision: 1.6.1
      chart: jetstack/cert-manager
      parameters:
        - name: installCRDs
          value: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
