ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: code.k3d.localhost
      paths:
        - '/'
        - path:
          backend:
            serviceName: code-server
            servicePort: 8080