apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    path: 'ci/helm-chart'
    repoURL: 'https://github.com/cdr/code-server'
    chart: code-server
    helm:
      valueFiles:
        - values.yaml
      values: 'ingress.enabled: true'
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true