apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tom333/demo_flask_k8s.git
      revision: main
      directories:
      - path: k8s/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: demo-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/tom333/demo_flask_k8s.git
        targetRevision: main
        path: k8s/'{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-flask
