apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-app
  namespace: argocd
spec:
  destination:
    namespace: vote
    server: https://kubernetes.default.svc
  project: registry-project
  source:
    path: registry/
    repoURL: https://github.com/tom333/argocd_kluster.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

